added the edit order page and made a route for it
Vinatta/frontend pull request #2
Opened 2021-08-10 09:34 UTC by ShivaKakarla512

No styling yet - WIP

2021-08-23 17:19 UTC, dhee9000 requested changes
Reviewed the code, looks great! There are a couple minor changes that I pointed out, fix and commit and it looks good.

2021-08-23 17:19 UTC, dhee9000 commented on .eslintrc
> +        "no-tabs": "off",
let's remove any eslintrc changes from PRs. let's use unix line endings, you should be able to change VSCode settings to edit with unix line endings too from the bottom right

2021-08-23 17:19 UTC, dhee9000 commented on package.json
> +    "@coreui/coreui": "^4.0.0-rc.5",
are we using the bootstrap version of coreui too? I think all components are also accessible from the React package but let me know if there is actually a dependency on the bootstrap package.

2021-08-23 17:19 UTC, dhee9000 commented on src/routes/index.js
> +		path: '/editOrder',
let's make the URL structure for this be /orders/<orderId>/edit. Ignore the <orderId> for now and just show the page for any orderId value

2021-08-23 17:19 UTC, dhee9000 commented on src/views/editOrderFields/EditOrderFields.tsx
> +import '@coreui/coreui/dist/css/coreui.min.css';
Does this do anything that the React import doesn't do?

2021-08-23 17:19 UTC, dhee9000 commented on src/views/editOrderFields/EditOrderFields.tsx
> +const documentType = [
lets move all of these constants into a separate file called something like EditOrderFieldsConfig.js or something like that (up to you if you have a better name).

2021-08-23 17:19 UTC, dhee9000 commented on yarn.lock
> +"@coreui/coreui@^4.0.0-rc.5", "@coreui/coreui@^4.0.1":
again same as package.json but if that updates so will this.

2021-08-24 01:31 UTC, koletimanish approved these changes
Looks good to me!

2021-08-24 19:40 UTC, dhee9000 approved these changes
Looks great! Ready to merge into develop.

2021-08-25 01:57 UTC, merged