added the view orders page and its components
Vinatta/frontend pull request #3
Opened 2021-08-13 14:45 UTC by ShivaKakarla512

WIP

2021-08-23 18:08 UTC, dhee9000 requested changes
Also looks great, I left some feedback, once it's addressed this one is good to approve too.

2021-08-23 18:08 UTC, dhee9000 commented on yarn.lock
> +"@coreui/coreui@^4.0.1":
same as package.json

2021-08-23 18:08 UTC, dhee9000 commented on src/views/viewOrdersStatus/components/ViewOrder.tsx
> +type Props = {
Similarly, IViewOrderProps

2021-08-23 18:08 UTC, dhee9000 commented on src/views/viewOrdersStatus/components/ViewOrder.tsx
> +type State = {
Similarly, IViewOrderState

2021-08-24 01:48 UTC, koletimanish approved these changes
Looks good to me!

2021-08-24 19:39 UTC, dhee9000 approved these changes
Looks great! Ready to merge in to develop

2021-09-21 01:39 UTC, dhee9000 approved these changes
Looks good!

2021-09-21 01:39 UTC, merged