added the landing page
Vinatta/frontend pull request #4
Opened 2021-08-19 04:09 UTC by ShivaKakarla512

Styles and assets may change

2021-08-23 18:13 UTC, dhee9000 requested changes
Great work on this, left some feedback but overall almost ready to approve.

2021-08-23 18:13 UTC, dhee9000 commented on .eslintrc
> +        "no-tabs": "off",
drop eslintrc changes, use Unix line endings

2021-08-23 18:13 UTC, dhee9000 commented on src/views/viewLandingPage/ViewLandingPage.css
> +@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap");
will get on call with you about this file

2021-08-23 18:13 UTC, dhee9000 commented on src/views/viewLandingPage/ViewLandingPage.tsx
> +import pic from './assets/doctorthree.svg';
let's use a more descriptive name

2021-08-23 18:13 UTC, dhee9000 commented on src/views/viewLandingPage/ViewLandingPage.tsx
> +							// onClick={() => loginWithRedirect()}
is this going to be uncommented in the future? if not let's remove commented lines

2021-08-24 02:09 UTC, MatthewKlayme approved these changes
looks good

2021-08-24 19:39 UTC, dhee9000 approved these changes
Looks great! Ready to merge in to develop

2021-09-21 01:40 UTC, merged